// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMlAFN3rtacmisi8rXzLEHAg2OtkvHLG8',
    appId: '1:321572846726:web:98f7dad02acc0d15a12507',
    messagingSenderId: '321572846726',
    projectId: 'reddit-clone-youtube',
    authDomain: 'reddit-clone-610f9.firebaseapp.com',
    storageBucket: 'reddit-clone-youtube.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvx8PcAvBHBnCPvkVNJ8FbD2D7UMXZ3V8',
    appId: '1:321572846726:android:33dbe0ada7a20614a12507',
    messagingSenderId: '321572846726',
    projectId: 'reddit-clone-youtube',
    storageBucket: 'reddit-clone-youtube.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdCg2QUCaZZR7ih4WnrT41W5nTBSUcu3c',
    appId: '1:321572846726:ios:84cfa635eea7de9fa12507',
    messagingSenderId: '321572846726',
    projectId: 'reddit-clone-youtube',
    storageBucket: 'reddit-clone-youtube.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
